Notify about errors.

diff --git a/plots/make_multiple b/plots/make_multiple
--- a/plots/make_multiple
+++ b/plots/make_multiple
@@ -14,6 +14,10 @@ do
 		do
 			echo "$f"
 			asy "$f" &> /dev/null
+			if [ $? -ne 0 ]
+			then
+				echo "  ERROR"
+			fi
 		done
 
 		cd - > /dev/null
